### ISSUE TITLE
Fix General Design issues on the site

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#100]
Two examples of design flaws we are having to illustrate what is needed:

1. After finishing the application process, this is what we are showing:
![image](https://user-images.githubusercontent.com/390030/32573557-2d532e1e-c4ad-11e7-97f5-d85af7214504.png)

And this is the mockup (how it should be displayed):

![image](https://user-images.githubusercontent.com/390030/32573577-3a60c8be-c4ad-11e7-8b47-b53f6deac46d.png)

Why are we not using this? Who should implement this? I'm not clear.

2. Navigating on the application, the site _stretch_ and expand vertically depending on how much text the central `<div>` has. Under the mockup [that's not the case](http://gustavocatalan.com/lab/cc-network). Is it a way to set the `<div>` on every page the same size to avoid this to happen? cc @robmyers

**Comment by robmyers** [comment]
1. If our designers are implementing this I need to receive it as modifications to the WordPress theme ( themes/cc-commoners) that work with the 2017 theme, BuddyPress and GravityForms that I can just install, and the accompanying content on Staging to copy over to Live.
If I am implementing this we need to schedule several days and I need to work out how to convert the sketches to WordPress.
The common constraint in both scenarios is that this has to work as WordPress content with the plugins we have built the site using (BuddyPress and GravityForms) based on the theme that the plugins work well with (2017, which cc-commoners is based on). Making entirely new layouts (as in the example above) is time consuming.
So this is a timing question. Can we start bootstrapping with something that works, then tune up the design? Or does it have to be done now, in which case we are pushing launch back further. This isn't my call, and I will do whatever is needed to make everything work. I'm just laying out the relative impacts of the options I can think of.

**Comment by robmyers** [comment]
2. Like this:

![image](https://user-images.githubusercontent.com/21746/32584172-ed935520-c4ab-11e7-8ad3-a14fdca93bbc.png)

![image](https://user-images.githubusercontent.com/21746/32584183-fc11ac46-c4ab-11e7-9f76-3a5c60428a92.png)

As the second image shows, shorter pages look a little strange but if this is OK I can commit the changes and install this version.
