### ISSUE TITLE
Add new /getinvolved page

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#103]
The idea here is to have a page to orientate visitors to different ways to get involved with CC following [what Jennie suggested](https://docs.google.com/document/d/1c-sKnGfbRKdwUzeiIfvugeanmCS_pNMpHeTOFbrxRUQ/edit?ts=5a03ce44) (new doc) some time ago.

My idea is to have it linked under the GET INVOLVED box on the homepage.

I will work on the page. I will ask @edmillag to help me out with some design.

**Comment by edmillag** [comment]
i agree with that, lets use one box underneath de slideshow as a link for this specific page

**Comment by robmyers** [comment]
Please construct this on the staging site so we can copy it straight over to live when ready.

**Comment by robmyers** [comment]
I assume this is for initial launch so I'm adding it to that milestone.
