### ISSUE TITLE
Clarify the text of the "approving" email

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#104]
![image](https://user-images.githubusercontent.com/390030/32577701-938ec452-c4b9-11e7-98ea-f7253eb17209.png)

This email is very confusing. If this is the email we are sending the Membership Council people (please clarify), we should work on this text to make it friendlier than this. 

Additionally, I would suggest **not to send it automatically but manually once a week** linking to the intern WP page with the list of the vouched applicants, indicating on the email a clear set of instructions about how to proceed. I can work on this text tomorrow, @robmyers

**Comment by robmyers** [comment]
We're limited in the information we can access in the form notification emails here. If this version isn't sufficient (and it's the best we can do at the moment, rather than the best that could be designed) then rather than creating a new email notification system we should not send an email notification at all and rely on the council checking the page on the site that lists new applicants regularly.

**Comment by peterspdx** [comment]
Ouch, says a future member of the interim council. I think some email prompt should go out. Or maybe it's a weekly reminder on every interim council members' calendar that pops up that requires reserving time on a weekly basis, or reminders to tend to pending requests. Something, please?

**Comment by robmyers** [comment]
I'm sympathetic to the council but I'm not sure how best to use the resources we have in the time we have to support them.

The notifications for each application were designed to be more granular and serve as a nudge but we are limited in how informative we can make them without a disproportionate amount of work relative the potential reward.

WordPress doesn't support weekly emails, and there is a page listing current applicants in the pre-approval state and in the vote/vouch/final approval state.

So I think a calendar reminder is probably the least bad solution?

**Comment by peterspdx** [comment]
OK. @claudioruiz Can you please set it up so that members of the council receive an auto email and/or a calendar entry and reminder on a regular basis set to how you'd like to have everyone review the then-pending applications? Agree it's probably the least bad solution.

**Comment by claudioruiz** [comment]
@peterspdx Yes, that's the best solution. That's why I suggested to send manually a communication once a week. We can definitely handle that. Not you, @robmyers (don't you worry), we can do that with Simeon. 

So:

1. We are not sending these emails.
2. We (@claudioruiz) are setting a process (kind of manual) with a calendar block each week for the Membership Council members to approve or deny new applications in a weekly basis.

**Comment by claudioruiz** [comment]
I'm getting nervous with so many issues open. @robmyers, can you please try to close those who are solved?
