### ISSUE TITLE
I can't see the carrousel at /

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#109]
No idea if you decided to get rid of it or it's just not implemented yet.

I think it's important because on that carousel we are explaining the page, why the network is awesome, etc, etc. Otherwise, we should explain that differently. 

Message for the home (this should also apply to the information displayed on the 3 boxes at the bottom)

* We **have** a network of people and institutions
* That network **is** awesome and it's a movement
* We **do** great things
* You **can** join and contribute

**Comment by edmillag** [comment]
Slideshow are disabled because there is no other content delivered for the slideshow than the "Get Involved" slide. We can add any content you want to the slideshow (2+ slides will be great)

**Comment by edmillag** [comment]
The main menu should have this content, and every slide should reinforce it:

- We have a network of people and institutions -> create page we are
- That network is awesome and it's a movement (We do great things)-> create page what we do
- You can join and contribute -> get involved

On the three other blocks, content should be:
-Individual Sign up
-Institutional Sign up
-The Charter
