### ISSUE TITLE
Individual sign-up is out of focus

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#110]
http://165.227.127.141/sign-up/individual/
![image](https://user-images.githubusercontent.com/390030/33556797-ee989cae-d8e3-11e7-889d-441dc1bdae0b.png)

You need to scroll down to see the entire text box. Is that a feature to be able to see the background image? O_o

**Comment by catalancho** [comment]
yes, it is a feature to keep the background visible. On another forms definitely should be out of focus (cause are longer forms). Ed and I don't think that is a problem. People know how to scroll.
