### ISSUE TITLE
Dialog boxes are not centered

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#113]
ex:

http://165.227.127.141/sign-up/individual/form/

see in action here: https://cl.ly/1n3H0w2d3y1B

**Comment by catalancho** [comment]
Vertically or horizontally ?

**Comment by claudioruiz** [comment]
Both vertically and horizontally. At least you are using a monitor of 90", you will always need to scroll, even if the information is not that long, as here http://165.227.127.141/sign-up/individual/form/
