### ISSUE TITLE
Let's add the CC license at the bottom

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#118]
We should use a CC:BY 4.0, such as creativecommons.org

**Comment by catalancho** [comment]
![photo_2017-12-26_23-36-30](https://user-images.githubusercontent.com/32273591/34369647-50826cfa-ea9c-11e7-8f3c-440e916cb22c.jpg)

**Comment by catalancho** [comment]
![captura de pantalla 2017-12-27 a la s 12 23 05 a m](https://user-images.githubusercontent.com/32273591/34369659-64a9aaea-ea9c-11e7-8be6-0cc7ee72b7b7.png)
