### ISSUE TITLE
Search Results Page Is Not Displaying Correctly

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#126]
Not just empty of results, plain white.

**Comment by robmyers** [comment]
Confirmed with theme properly merged.

**Comment by robmyers** [comment]
With #139 fixed, the search results page is no longer blank but is rendering strangely.

![image](https://user-images.githubusercontent.com/21746/34235957-f1415ebe-e5a9-11e7-9ffc-88d9ec48b97a.png)

**Comment by catalancho** [comment]
Hola @robmyers, tell me if this work for you 
78c92ff: Now the 'page-template-page-faqs' template could be used in the search results page (by looping the post results inside it), the accordion will not be shown collapsed.

**Comment by robmyers** [comment]
See also #95.
