### ISSUE TITLE
/sign-up/individual/form/ Top Margin Hides Form Top, And There Is No Background Image

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#133]
This doesn't even show the shortcode text, the page under the header menu is just blank white.

**Comment by robmyers** [comment]
Nothing in the logs.

**Comment by robmyers** [comment]
The top margin is -27% on the .signup-form-body on this page and it has a different layout / no background image compared to the institutional form (that page looks great!):

![image](https://user-images.githubusercontent.com/21746/34235044-e4da898a-e5a3-11e7-94c8-a34fdbbdb8aa.png)

If I start applying as an Institution then visit the Individual Form page, the "You are already signing up as an Insitution" message is rendered, but is hidden behind the top banner:

![image](https://user-images.githubusercontent.com/21746/34235123-5b8d3fd2-e5a4-11e7-97b3-83501552af31.png)

**Comment by gradiente** [comment]
Solved in desktop http://165.227.127.141/sign-up/, working on the mobile breakpoints behaviour.

**Comment by catalancho** [comment]
Mobile ok
![photo_2018-01-04_14-39-26](https://user-images.githubusercontent.com/32273591/34576588-219752bc-f15d-11e7-9c35-6c009a281325.jpg)
![photo_2018-01-04_14-39-29](https://user-images.githubusercontent.com/32273591/34576589-21c2fab6-f15d-11e7-90d3-57314cb06105.jpg)
