### ISSUE TITLE
SSL cert problem, not loading

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#137]
https://commoners-staging.creativecommons.org/

**Comment by robmyers** [comment]
I turned off CloudFlare while trying to work out what was breaking the new version.

I've turned it back on but I wouldn't bother testing anything until I've worked out how to merge things and deployed them.

**Comment by claudioruiz** [comment]
understood. waiting for the signal to start testing it out ;)

**Comment by robmyers** [comment]
@claudioruiz 

![](https://media.boingboing.net/wp-content/uploads/2017/06/giphy-5.gif)
