### ISSUE TITLE
/sign-up/ appears blank with wide window

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#141]
With a wide window, /sign-up/ looks like this:

![image](https://user-images.githubusercontent.com/21746/34236194-118a7826-e5ab-11e7-8e7c-6006d4e8af6e.png)

If I make it too narrow, it looks like this:

![image](https://user-images.githubusercontent.com/21746/34236211-24d8bf00-e5ab-11e7-967f-00f6a8bb8a21.png)

In-between, it looks like this:

![image](https://user-images.githubusercontent.com/21746/34236226-3df137a6-e5ab-11e7-9da0-67059ba4b95e.png)

I think this may be part of the same family as #133 and possibly #126 .

**Comment by robmyers** [comment]
Note the vertical slider position on this screenshot of /sign-up/individual/

![image](https://user-images.githubusercontent.com/21746/34236337-ec486e64-e5ab-11e7-8642-9ce175aa5b05.png)

**Comment by robmyers** [comment]
All the sign-up pages and forms have this issue since the #139 fix.

**Comment by robmyers** [comment]
This is better on some pages with 28fc930ef9eaf2f25445a2203de240fab90c14d4 .

/sign-up/ has this problem, though (and it's on the dev site 165... as well).

**Comment by gradiente** [comment]
Solved in desktop http://165.227.127.141/sign-up/, working on the mobile breakpoints behaviour.

**Comment by catalancho** [comment]
it's ok on mobile 
![photo_2018-01-04_14-17-53](https://user-images.githubusercontent.com/32273591/34575689-7202101e-f15a-11e7-9093-1cffa97ff1bd.jpg)
![photo_2018-01-04_14-18-00](https://user-images.githubusercontent.com/32273591/34575692-72478798-f15a-11e7-85cb-4e1fd69979d8.jpg)
