### ISSUE TITLE
Last fix for the Charter?

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#143]
Is it possible to re-check the CSS for the Charter for better looking?

It looks to me we just edited the H1, H2, etc, but nothing else. For instance, the paragraphs do not have space in between (so it looks as a big chunk of letters), the "Note" under Code of Conduct looks unformatted, etc.

It shoulnd't be super hard, isn't it?

**Comment by catalancho** [comment]
http://165.227.127.141/charter/
