### ISSUE TITLE
/policies page, needs updating to account for members in addition to affiliates

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/commoners#147]
Diane is updating

**Comment by robmyers** [comment]
@peterspdx is this OK to close?

**Comment by robmyers** [comment]
@peterspdx I pressed the wrong button. Sorry about that.

**Comment by robmyers** [comment]
@peterspdx ping wrt this. :-)

**Comment by peterspdx** [comment]
@little-wow updated that page awhile back, so this can be closed. Noting however, that before we do, could someone please fix a typo that I just spotted?

In the italicized note just under the table of contents, "of" in the phrase below should be "or". Thanks.

an Individual Member of Institutional Member of the CCGN

**Comment by robmyers** [comment]
I have made that change.

Thank you!
