### ISSUE TITLE
FAQ not displayed

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#148]
This must be silly, but I just added [the FAQ text on the FAQ page](https://commoners-staging.creativecommons.org/wp-admin/post.php?post=149&action=edit) but is not displayed on the [FAQ page](https://commoners-staging.creativecommons.org/faqs/). I guess is something about the template I didn't find out. 

I did not find the way to edit that page. Help?

**Comment by robmyers** [comment]
The FAQ page content is currently hardcoded in themes/cc-commoners/page-faqs.php .

I will convert the template to be a template rather than a static page, then the content will display.

**Comment by robmyers** [comment]
I reformatted the HTML quite extensively in WordPress to match the HTML in the page. The
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;
blocks are an attempt to match the formatting in the previous WordPress version. Having two newlines/an empty line breaks the rendering so this was the closest I could get. We can reformat it further to try and improve this if needed.

**Comment by claudioruiz** [comment]
I made some tweaks directly on WP. Is not perfect, but I think it's ok to go. We can improve it later.
