### ISSUE TITLE
Add up the Interim Membership Council as members and give them approving powers

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#149]
This is the list of people: https://github.com/creativecommons/global-network-strategy/blob/master/docs/the-interim-membership-council.md

Those people will be members on day 0 and will have approving powers.

**Comment by robmyers** [comment]
They will need to log in once with CCID and ignore the sign-up process.

I can then give them the correct admin permissions.

**Comment by claudioruiz** [comment]
Should they do that now on Staging? 
I'm asking because the Staging database has a lot of test users. 

Whatever works better for you, Rob.

**Comment by robmyers** [comment]
I'll remove the test users and approve the council members who are already on there.

**Comment by claudioruiz** [comment]
@robmyers I already talked with Ryan. We will be contacting all IMC members one to one. For that to happen we need [your inputs on this document](https://docs.google.com/spreadsheets/d/1mZqvL8Vgv_5M618V5uZedwUU_dSu2v_03ywKgtd4glk/edit?usp=sharing). Please put there if we are OK with them or if we need them logged in. 

We should send **those emails by today**. Please prioritize this.

**Comment by robmyers** [comment]
I have updated the document to reflect the current state of affairs

Not everyone is using the same email address for their CCID as is referenced in the document, so where I have marked someone as "No CCID for this address" they may have a CCID for a different email address, but they have definitely not logged in to staging using *any* CCID account.

Where someone is marked as "Logged in, promoted" they are signed up on staging, have been copied to live, and are good to go.

**Comment by robmyers** [comment]
@claudioruiz We have one hold out , see the doc.

They need to create a login.creativecommons.org account.

They should then log in at network.creativecommons.org directly, and I can then make them a member of the council role there.

**Comment by claudioruiz** [comment]
Ok, np.
