### ISSUE TITLE
Fix the WP roles

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#152]
![image](https://user-images.githubusercontent.com/390030/34879016-9811a9c8-f78a-11e7-9772-54e4a0f780bc.png)

It's confusing. 

We should have:
* Admin 
* Individual Applicant 
* Institutional Applicant 
* Membership Council (can vouch and approve applications) 
* Membership Final Approver (Claudio/Legal?)
* Individual Member (can vouch)
* Institutional Member

**Comment by robmyers** [comment]
This is a result of the roles changing during development and the database not being cleaned up.

I will remove the old names.

The current roles are:

**Built in to WordPress:** Admin, Editor, Author, Contributor, Subscriber.

**For The Site Workflow:** New User, Membership Council, Membership Final Approver, CC Legal.

The last six states shouldn't be there. If they can be removed I will remove them. If they are being created by something else then they'll have to remain.

**Comment by robmyers** [comment]
Removed.
