### ISSUE TITLE
We need a guide for Membership Council for approval

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#153]
We need this. 
I can help you out writing it. It shouldn't be that long. Short and sharp.

It's connected with https://github.com/creativecommons/commoners/issues/149 because I want to send just one email: this is what you should do (including logging in with CC ID)

**Comment by peterspdx** [comment]
Let me know how I can help, and if I can review. Thx.

**Comment by claudioruiz** [comment]
done https://github.com/creativecommons/global-network-strategy/blob/master/docs/Guide_for_approve_new_members.md#how-to-approve-new-members
