### ISSUE TITLE
Improve the 404 page

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#155]
this content https://github.com/creativecommons/commoners/issues/95#issuecomment-343149969 instead of the weird dark grey rectangle 
![image](https://user-images.githubusercontent.com/390030/34881438-508a9422-f792-11e7-8fea-1d1480111882.png)

**Comment by robmyers** [comment]
Button size fixed but I agree we need a better 404 page as specified in #95 .

**Comment by hugosolar** [comment]
404 page redesigned
https://network.creativecommons.org/404
