### ISSUE TITLE
How can I edit the /get-involved page?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/commoners#161]
https://network.creativecommons.org/get-involved/

There are a number of errors on this page and I would like to edit it, but the text appears not to be in WP. How can I fix it?

**Comment by robmyers** [comment]
It's here -

https://github.com/creativecommons/commoners/blob/28fc930ef9eaf2f25445a2203de240fab90c14d4/themes/cc-commoners/hub-page.php

**Comment by little-wow** [comment]
updated text, hoping it gets merged :crossed_fingers:

**Comment by robmyers** [comment]
it was merged. :-)

The next time we want to update the text we should extract it from the template and get it into WordPress.
