### ISSUE TITLE
Fix wp-admin on network.creativecommons.org

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#162]
`https://network.creativecommons.org/wp-admin/` redirects to `https://network.creativecommons.org:8080/wp-admin/`

and `ERR_SSL_PROTOCOL_ERROR`

You can't get in.

**Comment by robmyers** [comment]
"I'm not seeing that", which obviously doesn't help you. I've changed the configuration, try now?

**Comment by claudioruiz** [comment]
Now it works, but I lost all my superpowers. I need those.

**Comment by robmyers** [comment]
I removed the kryptonite from the database. Please try now.
