### ISSUE TITLE
There is no way to finally approve vouched applicants

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#164]
For instance, apparently Renata instead of logging in with CCID, she just applied for being a member with another email. Anyway, now she has the 2 votes, but I can't finally "accept her". 

![image](https://user-images.githubusercontent.com/390030/35040478-f1e4b8cc-fb5f-11e7-8a61-8d493365c184.png)

Just for the sake of her vouching powers for the moment of the launch, I change the permissions of her gt.creativecommons.org email (the one you created). But we need to merge that with the "applicant profile" she created and I can't approve as a member.

**Comment by robmyers** [comment]
Oh people need more votes than vouches. The amount may be too high - it's currently set to five.

**Comment by claudioruiz** [comment]
you are totally right. my mistake.
