### ISSUE TITLE
Allow admin to change requested voucher and re-assign it to other member

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#167]

**Comment by robmyers** [comment]
This actually can't be done manually at the moment, which surprised me, so it will be a little bit more involved than I expected. I'll work on it.

**Comment by claudioruiz** [comment]
And how exactly you can do that on the Dashboard?

**Comment by robmyers** [comment]
Ah it's not hooked in on the dashboard. The code to generate the link is implemented, I will add it to the application page.

**Comment by robmyers** [comment]
Until I hook this in, add the user id # to the end of this url -

https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application-change-vouchers&user_id=

e.g.:

https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application-change-vouchers&user_id=38

You can get the user ID from the user approval page

**Comment by robmyers** [comment]
OK this is hooked in for you only (with the """pre-approver""" role) from the "Vouchers" section of the Applicant approval page and as a menu item on the user list:

![image](https://user-images.githubusercontent.com/21746/36574738-f4ffb7a6-17fb-11e8-8687-d797630dce90.png)

![image](https://user-images.githubusercontent.com/21746/36574790-30ee849a-17fc-11e8-834c-b6e700b1ba4f.png)

Commit c43dee61310877f7afd879a175db3841c7b909aa .
