### ISSUE TITLE
WordPress Shouldn't Strip + in Emails To Create User Login

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#168]
It won't match incoming logins.

**Comment by robmyers** [comment]
Here's how WordPress strips characters from usernames:

https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/formatting.php#L1834

We need usernames to be emails so we can look them up with CAS. Email addresses allow more characters than WordPress usernames:

https://stackoverflow.com/a/2049510

We should create a filter to Do The Right Thing but this may be hard in the general case as there are several filters that get run already.

**Comment by robmyers** [comment]
For the moment, just be aware of this class of support calls.

**Comment by claudioruiz** [comment]
is this solved, right?

**Comment by hugosolar** [comment]
A filter to avoid this was added
Still, I'm going to run some tests in order to check everything is ok

**Comment by hugosolar** [comment]
Checked with a test account
