### ISSUE TITLE
A single member can vouch 4 times for the same application (!!)

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#169]
Kelsey did vouch 4 times for the same applicant: 

![screen shot 2018-01-18 at 9 45 19 am](https://user-images.githubusercontent.com/390030/35098833-7ad97f62-fc34-11e7-9b51-a44f0eb34736.png)

**Comment by claudioruiz** [comment]
maybe a mobile glitch?

She said she approve it on mobile ![image](https://user-images.githubusercontent.com/390030/35099289-2f7b3068-fc36-11e7-8dd3-57e47e7ae391.png)

**Comment by robmyers** [comment]
No that's just a special mode for Kelsey. ;-)

Yes this is bad, there's code to check to see whether someone has already vouched but it didn't catch this. I will look into it.

Thank you for reporting this!

**Comment by robmyers** [comment]
I've updated the caching settings to address Paul's comments and hopefully that will help with this as well. I'm still looking at the code, we do check for entries so the logic must be bad somewhere.

**Comment by robmyers** [comment]
I'm going to close this as we haven't had any more instances reported. If it happens again I will update the counting logic - we cannot catch it in the form saving logic unfortunately.

**Comment by robmyers** [comment]
I want to put some protection against this being *counted* in place.
