### ISSUE TITLE
Update Open Graph Metadata

### ISSUE THREAD

**Issue by little-wow** [creativecommons/commoners#174]
https://developers.facebook.com/tools/debug/sharing/?q=network.creativecommons.org

https://cards-dev.twitter.com/validator

**Comment by robmyers** [comment]
Missing Properties
The following required properties are missing: fb:app_id

**Comment by claudioruiz** [comment]
I don't know what is this, I can't prioritize.

**Comment by little-wow** [comment]
For sharing on social to debug the metadata so it shows up right. Also improves SEO and indexing.

**Comment by hugosolar** [comment]
Yoast SEO plugin was added
This plugin improves social media sharing metadata and SEO
