### ISSUE TITLE
Add an option for vouchers to DECLINE to vouch different to reject

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#175]
Today vouchers just can Approve or Deny. 

We should add an option where vouchers can DECLINE to vouch, with a different effect. Decline meaning sending an email back saying some or all of the vouchers declined your vouching request. Go back and find a person who personally knows you and your work who can vouch you.

**Comment by robmyers** [comment]
This will require an extra screen and an extra email as well as the option, as well as modifying the logic for notifying and checking Vouchees.

We can combine the development for this with the admin ability to change the Vouchers in #167

How urgent is this? It is probably the largest chunk of work in the issues at the moment.

**Comment by claudioruiz** [comment]
I would say is kind of urgent, to be honest. Today we have a bunch of applications _on hold_ because the voucher don't have an option different than deny to vouch someone she don't know. The workflow does not answer that because, in strict sense, that application does not exist if does not have the vouches. But today we are stuck because it shouldn't be the same not get the vouches and your application to be denied. 

I would schedule a call with legal early next week to check this out. But whatever we decide, the development is urgent.

**Comment by robmyers** [comment]
Implemented.
