### ISSUE TITLE
Create a dashboard for managing the members

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#180]
This is not #1 priority today but it might be in 1 month when Chapter meetings start happening.

What we need (inside or outside WP for the use of the Network management team):

* Be able to see an updated list of members of the network, with their metadata (name, country, email, interests, vouchers, etc)
* Being able to sort them in different ways, as in a spreadsheet.

Nice to have:
* Way to send them communications by email.

**Comment by peterspdx** [comment]
Perhaps separate issue, but https://network.creativecommons.org/wp-admin/admin.php?page=global-network-legal-approval doesn't show pending institutional members. That's at least not available to me. Would be nice to see institutional members with vouching stage status in additional to the legal approval page (which is completely empty at the moment).

**Comment by robmyers** [comment]
@peterspdx Legal won't see Institutions until they've been Vouched, Voted and Approved.

We do seem to have a bottleneck on Institutional applications, I am going to look at the data.

**Comment by claudioruiz** [comment]
Just checked. By today, we have 4 Institutional applications, 3 of them with just one vouch and 1 with a declining.

**Comment by peterspdx** [comment]
Can you make it so that the applicants are visible to the imc, similar to the individual members? Or am I missing something?

**Comment by claudioruiz** [comment]
IMC just can see the applications when they have 2 vouches. Same is true for institutions and individual applications. At the beginning, it was possible for the IMC to see every single application, but that was a mess.

**Comment by robmyers** [comment]
Individual and institutional member listing and list of emails implemented.

Sorting pending.

**Comment by robmyers** [comment]
For search I assume we want:

Approval date
Country
Chapter
Interests
Languages

We can also search for:

Vouchers
Voters

But these are more computationally expensive.

A full-text search on Bio or URLs would also be expensive.

**Comment by claudioruiz** [comment]
@robmyers what do you mean for search? I'm lost.
