### ISSUE TITLE
Implement workflow of vouching not answering requests

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#182]
* Set a rule of 10 days for vouchers to react to requests. 
* On day 10, we send an email to the voucher/s requiring them to answer within 3 days otherwise the application is declined.

**Comment by robmyers** [comment]
Same as #192, but leaving open to track the three day decline.

**Comment by claudioruiz** [comment]
I understand this was closed with https://github.com/creativecommons/commoners/commit/0c2f08bff693741330b1e8966186752011115fd1
