### ISSUE TITLE
Feature New Members of the week on the front page

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#186]
Use plugin? Failing that, use the BuddyPress member loop to display new members.

Talk to the designers about integrating this in a visually appealing way.

**Comment by robmyers** [comment]
@claudioruiz Can we talk to the designers about this?

**Comment by hugosolar** [comment]
- Post type featured members 
   - Featured member statement
   - Featured member profile picture as fallback (in case user doesn't have any profile pic)
- Homepage Widget created
