### ISSUE TITLE
Check that form is clear enough that people should not choose vouchers from their own institution

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#189]
We may need to add text.

**Comment by claudioruiz** [comment]
@robmyers I couldn't find where Institutional Applicant picks its vouchers after filling the info https://network.creativecommons.org/wp-admin/admin.php?page=gf_edit_forms&id=46

Are we using the same form for both institutional and individual members?

**Comment by robmyers** [comment]
We are.
