### ISSUE TITLE
Send email reminder after 10 days voucher not answering a request

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#192]
* 10 days: trigger email
* if no answer after 3 days after the email, automatically _decline_ and ask the applicant to ask for other vouchers.

**Comment by robmyers** [comment]
I have the code to identify old requests and email them in place.

I need to set up the 10-day repeating job code and then test this so we don't spam anyone!

**Comment by claudioruiz** [comment]
Good. Let's do this! We already have a queue of people not vouching other. 
Keep in mind in the past when we implemented the "decline" option, we had a group of members (applications made before the fix) in the vacuum, not receiving any email. Please let's avoid that.

**Comment by robmyers** [comment]
This took some debugging.

It is scheduled for Mondays, GMT.

**Comment by claudioruiz** [comment]
awesome! 
quick q: are we certain this will apply *also* to applications already in the process? (avoiding what happened with the last decline fix)
