### ISSUE TITLE
Declined applicants can't pick different vouchers

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#193]
When an applicant already declined tries to log in to change her vouchers, this is what she sees:

![img_20180219_120936_216](https://user-images.githubusercontent.com/390030/36384859-7f848238-156f-11e8-96af-88457064728d.jpg)

That's a real example of [an applicant from Uruguay](https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application&user_id=81). (One of the ones not receiving an email when they were declined)

**Comment by claudioruiz** [comment]
Same issue reported by Nerida from Australia.

**Comment by claudioruiz** [comment]
Same for Gunnar from Mexico

**Comment by robmyers** [comment]
Fixed in e595e6c .

Deployed to live.

**Comment by robmyers** [comment]
Let me take a look on Friday/tomorrow PST.

**Comment by claudioruiz** [comment]
![image](https://user-images.githubusercontent.com/390030/36614573-f165b576-18bb-11e8-97a7-e673ad01d093.png)
Ileana from UY is reporting the same issue with a screenshot.

**Comment by robmyers** [comment]
If the requested Voucher has already Vouched for you then you cannot change them and so their name will be displayed greyed out (as in the screenshot). This is expected behaviour but needs explaining better so as not to justifiably frustrate people.

**Comment by robmyers** [comment]
Ah that wasn't the issue, my apologies.

@gwolf @claudioruiz The "There was a problem" bug has now been fixed and deployed to live. Please retry.
