### ISSUE TITLE
received vouching request with applicant not identified

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/commoners#195]
Screenshot attached.
![screen shot 2018-02-26 at 9 27 11 am](https://user-images.githubusercontent.com/6153527/36678839-6ca2135c-1ad7-11e8-9bc6-51cae74d7399.png)

**Comment by claudioruiz** [comment]
@sarahpearson what application number this application has? (look at the URL)

**Comment by sarahpearson** [comment]
38

**Comment by claudioruiz** [comment]
It looks to me as an empty user. Odd. 
Maybe @robmyers can help us removing the user.
