### ISSUE TITLE
Institutional Membership declined can't pick new vouchers

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#196]
This has been reported by ISOC Bulgaria

> When I go to https://network.creativecommons.org/sign-up/institution/
> and login (veni@veni.com), and click on "let's get started", I get the following message (see below), but nothing about finding a new member to vouch for us. 
> *THANK YOU FOR APPLYING TO JOIN THE CREATIVE COMMONS GLOBAL NETWORK*
> Your application has been received.
> It will take several days to be reviewed.

@robmyers user_id=146

**Comment by claudioruiz** [comment]
ping?

**Comment by robmyers** [comment]
They had a "no" vote from before the "don't know" era, so I changed it.

They should be able to choose now.
