### ISSUE TITLE
Configure Test Instance of BuddyPress

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#2]
Develop the test instance of BuddyPress so we can just copy it for the live instance.

**Comment by robmyers** [comment]
Reviewing themes atm.

**Comment by soohyunpae** [comment]
Hi @robmyers, 

The current theme looks nice to me - it has a similar feel to CC website. 
Do you mind reviewing this doc https://docs.google.com/document/d/1zCdus-dJom7v_14FHxLd871s9NrL4GrOOgvXhclJi-o/edit#heading=h.s7vrha1njb6t and seeing if you can help add the things listed there? Thanks a lot!

**Comment by soohyunpae** [comment]
Hi @robmyers 

It seems the test instance is down. "Error establishing a database connection"
I'm sorry to bug you again, but we need to have a draft ready for review by this week!
Thank you!!

**Comment by robmyers** [comment]
Heya @soohyunpae .

It's back.

This is my top priority. I'm working on some things we need on my local machine, and then I'll recreate what we've got on a proper staging server tomorrow.

I'm hoping to get most things done by then, with the notable exception of automatic vouching (it will have to be manual at the moment).

**Comment by soohyunpae** [comment]
You are awesome @robmyers !!

I don't want to bother you while you are working hard on it. Just let me know when it's done, and I'd be happy to see what I can do to make your work easier. Feel free to let me know if there's anything I can do in the meantime.

**Comment by robmyers** [comment]
OK the site is now at:

https://commoners-staging.creativecommons.org/

I'll be adding stuff today but this morning is all meetings. :-/ :-D

**Comment by robmyers** [comment]
Thank you @soohyunpae :-)

**Comment by robmyers** [comment]
@soohyunpae I've added some new plugins to make things behave more as specified. See my comments on the doc. I'll do some tweaking tomorrow (particularly of the Theme settings) but this should be most of the functionality that we want to start with, apart from Vouching (next week..).

**Comment by soohyunpae** [comment]
Wonderful! I think automatic vouching can wait until next week. :D

**Comment by robmyers** [comment]
Very done.
