### ISSUE TITLE
Usernames are not displayed on Applications for Approval! 

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#201]
Fixing https://github.com/creativecommons/commoners/issues/183 broke the Applications for Approval list. Now we can see different colours, but no usernames!:

![image](https://user-images.githubusercontent.com/390030/37342121-64ad4550-26a2-11e8-83bd-4d6d59f8c097.png)

**Comment by robmyers** [comment]
Eek! Fixing.

**Comment by robmyers** [comment]
Fixed and deployed to live. Thank you for reporting this!
