### ISSUE TITLE
Voucher Requests menu item not displayed

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#204]
Caro Botero just reported this. She couldn't find the menu item to vouch people, she did it with the direct link I provided. 

The problem was the menu item was not displayed on her side. Screenshots logged: 

![image](https://user-images.githubusercontent.com/390030/37409385-00c919ca-277d-11e8-9671-7edf2835f368.png)

I don't have that problem when I visit the page. Can we check this?

**Comment by robmyers** [comment]
See also: #199

**Comment by robmyers** [comment]
The permissions for the Vouchers entry were wrong in the menu.

I've changed them and the entry should show for Members now.
