### ISSUE TITLE
Set automatic email to applicants with declined vouching still appearing

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#207]
- What to do: send them reminding email after 10 days of the first notification
- Saying: "remember you need to pick new vouchers, otherwise we will remove your data."
- How many we have today: 5

I guess this is connected with https://github.com/creativecommons/commoners/issues/192. Couldn't find the way you implemented the automatic email for declined vouchers. Because this is working, right?

**Comment by robmyers** [comment]
What's the "how many we have today" part?

I will add this based on the #192 code. We should review the emails for both.
