### ISSUE TITLE
Member Name doesn't show on profile pages

### ISSUE THREAD

**Issue by meredithjacob** [creativecommons/commoners#208]
When you click on a Global Network member name, their basic biographical data (Firstname, Lastname) doesn't display on their member page.

**Comment by robmyers** [comment]
Hmm. This will be a BuddyPress thing. It display's people's Global name. I'll see whether this is something we've accidentally taken out or it's something we need to add.

Thank you for reporting this!

**Comment by robmyers** [comment]
It's more complex than it looks. :-) The user name isn't displaying because we have the 'activity' module of BuddyPress disabled. If it wasn't disabled, we'd have to hook one function. Because it is, we have to hook another. Which I have now done.
