### ISSUE TITLE
Links on Profiles renders wrongly

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#213]
When a profile has more than 1 URL, those URLs shows merged:

![image](https://user-images.githubusercontent.com/390030/38501958-93a1393c-3be4-11e8-9bcd-77b4fbf36e21.png)

Example: 

https://network.creativecommons.org/members/valenzine/

**Comment by claudioruiz** [comment]
would you quickly check this, @hugosolar ? I'm adding it up to HS Sprint 2

**Comment by hugosolar** [comment]
This is a user problem
the Social media field is an open text field so the user can write freely
in this specific case the user write the url wrongly

![captura de pantalla 2018-11-14 a la s 08 29 37](https://user-images.githubusercontent.com/894708/48480035-e299ec00-e7e7-11e8-8de4-7233eee97148.png)

I fixed it in the Wordpress dashboard giving it a line break

**Comment by claudioruiz** [comment]
Ok, great. Maybe we can improve the style on the form in future iterations.
