### ISSUE TITLE
Notify legal@ when there's a new approved Institutional Member

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#214]
We need an email to nudge legal@cc there's a new Institutional application waiting for paperwork

**Comment by robmyers** [comment]
From Sarah's comment I remember this being out of scope - Legal are meant to check for new applications in the same way as the IMC.

**Comment by peterspdx** [comment]
We're talking about two things. One, emailing legal@ to alert them that the application is ready for legal review. The other, emailing the team to let them know status of application, and it's now with legal.

I suppose we can resolve this by requiring Sarah and Diane (me) to check the queue one or two times per week, and alerting the applicant that it's in the queue and with legal at that time. It's an extra step, it would be nice to have a simple auto email sent to the applicant.

It would also still be nice to have legal@ pinged once it moves from vouching and Claudio approval to legal for approval.

**Comment by claudioruiz** [comment]
Re: the email to the applicant, that was fixed here https://github.com/creativecommons/commoners/issues/50

Re: the email to legal, it's a nice to have, agreed.
