### ISSUE TITLE
Email triggering apparently not working

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#216]
Nevertheless what we fixed [here](https://github.com/creativecommons/commoners/issues/182), I have a request of someone applying for membership on March 26, with 1 vouch and 1 non-answering. 

Supposedly this will trigger an email to the non-responsive voucher 10 days after the vouch (April 5, in this case) giving her a due of 3 days otherwise it will be automatically declined. But that application (id=261) still appears with just 1 vouch. The applicant reached me out, meaning **he didn't receive any email** whatsoever explaining the declining vouch. 

This is critical and we need to check if the email triggering is working. I'm changing the priority to Urgent.

**Comment by robmyers** [comment]
OK! That should have run now, I see a stream of emails in the logs.
