### ISSUE TITLE
no favicon in https://network.creativecommons.org

### ISSUE THREAD

**Issue by syam3526** [creativecommons/commoners#217]
there is no favicon in https://network.creativecommons.org

**Comment by hugosolar** [comment]
The favicon URLs referenced in the code were fixed
now I'm able to see the favicon
![captura de pantalla 2018-11-13 a la s 10 49 32](https://user-images.githubusercontent.com/894708/48417602-e66b3700-e731-11e8-899b-14ef25191a05.png)

**Comment by syam3526** [comment]
awesome
