### ISSUE TITLE
CC Certificate: platform updates

### ISSUE THREAD

**Issue by jennryn** [creativecommons/commoners#221]
@robmyers When might you have updates on 1) migrating content from the Lumens instance of Pressbooks our own version of Pressbooks; 2) Our WordPress with PressBooks plug in and LTI plug-in(s), 3) testing CC hosted PressBooks integration (via LTI) to Canvas?  Thank you!

**Comment by robmyers** [comment]
1 and 2 are now complete.

I am moving 3 to the certificates project issue tracker.
