### ISSUE TITLE
Implement a workflow for pending not updated applications on the Spam Check

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#223]
Considering [the workflow I put here](https://github.com/creativecommons/commoners/wiki/Workflow-for-new-members-applications), we should implement the automatic wipe of old application with no new vouchers picked after the notice we send. 

We should implement a workflow for what to do with applications we already ask for updates and not answering in a while, send them a reminder and then later giving the admin an option of disable them (?) or just wipe them off

**Comment by claudioruiz** [comment]
‘wp-admin/admin.php?page=global-network-application-spam-check’

Users listed there are are either waiting for been

Under ‘received’ status. Not pre-checked by the admin
Pre-checked and asked for submit more information on their application
2.1. Under ‘update-detail’ status, meaning updated information already requested has been not yet submitted
2.2. Under ‘updated’ status, meaning applicant already updated its application with updated information, as requested.
What happen today is we have a list of applications under ‘update-detail’ status, where applicants has been not updating their application but we have no way to close those applications.

What we need is a way to close those applications after a X period of time. My suggestion:

After 7 days after we asked them for update their applications not receiving answer, system should send a reminder.
After 5 days still not receiving that updated information, system should send a new reminder letting them know have 3 more days for updating, otherwise the application will be closed.
So, 3 days later, automatically close the application not being updated.
If that’s very complicated, we can do it manually :)

**Comment by hugosolar** [comment]
Tested and done in https://github.com/creativecommons/commoners/pull/306
