### ISSUE TITLE
Search is not working at https://network.creativecommons.org/members/

### ISSUE THREAD

**Issue by jorgeandr3s** [creativecommons/commoners#225]
I searched for "Carlos", "Correa", and "Carlos Correa" in Members. 
I see "Carlos Correa" is a member but all searches returned "Sorry, no members were found."
![image](https://user-images.githubusercontent.com/8660163/40011814-8a9ea11c-576e-11e8-80ef-243b01cbf8c4.png)

**Comment by claudioruiz** [comment]
I'm sorry. I just [tried searching](https://network.creativecommons.org/members/) for "correa" and Carlos Correa is one of the matches.
