### ISSUE TITLE
Put rejected applications on hold

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#233]
When an IMC member vote negatively for an application, we need that application to receive an "on hold" -or similar- status to avoid other IMC members to vote positively and therefore for this application going to "approval" status. 

In terms of workflow, we need a list of these applications for the Global Network Council to deal with them when is formed.

**Comment by robmyers** [comment]
Related to #239 ?

**Comment by robmyers** [comment]
Their status was listed as "Declined" but this was poorly phrased so:
1. An applicant who has received sufficient votes against will now have their status listed as "Voted Against" on the approval list page.
2. It is not possible to vote for or against such an applicant on their application page. Instead a message explaining that they have been Voted Against is displayed.

**Comment by robmyers** [comment]
I can further highlight the entries on the list page or otherwise make them more obvious. Or I can break this out into a separate list page later.
