### ISSUE TITLE
Remove user_id=304 because it's duplicated

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#234]
https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application&user_id=304

**Comment by robmyers** [comment]
I cannot reproduce this. Can you email me a screenshot?

**Comment by claudioruiz** [comment]
![image](https://user-images.githubusercontent.com/390030/40620848-5e561b30-6268-11e8-8f1f-2e9c80d9a206.png)

**Comment by claudioruiz** [comment]
OK, fair. @simeonoriko can you please be in touch with this 2 people to figure this out? Thanks!

**Comment by claudioruiz** [comment]
@simeonoriko PING

**Comment by claudioruiz** [comment]
@simeonoriko ????
