### ISSUE TITLE
Add a "reason" field for better know why an application was declined

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#235]
This field should just be seen by the IMC. 

I don't think this is against the privacy policy at all, but pinging @sarahpearson in any case.

**Comment by robmyers** [comment]
This would be on vouches.

**Comment by robmyers** [comment]
We did remove this explicitly,for policy reasons, but it's simple to turn it back on at a technical level.

**Comment by robmyers** [comment]
@sarahpearson ping as per our conversation.

**Comment by robmyers** [comment]
@sarahpearson ping as per our conversation.

**Comment by robmyers** [comment]
@claudioruiz Just double-checking that this would be on vouches prior to following up with Legal. Am I correct in thinking this? Thanks.

**Comment by claudioruiz** [comment]
sorry I missed this comment. Yes, this was required by MC for vouchers. The idea is to have more granular information about why a voucher declined to vouch someone. Is that clearer?

**Comment by claudioruiz** [comment]
Remove that information from the application when it's finally approved. We don't need to keep that log.

**Comment by hugosolar** [comment]
Done
