### ISSUE TITLE
Check why the list of members export is incomplete

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#236]
the result under this is incomplete: https://network.creativecommons.org/wp-admin/admin.php?page=global-network-list-users

Is there a limit somewhere in the database for this export?

**Comment by robmyers** [comment]
Depending on how we measure it, there are 9 or 29 entries missing at the moment.

**Comment by robmyers** [comment]
We don't list institutions, so that excludes some entries.

**Comment by robmyers** [comment]
There seem to be 50+ entries missing.

I tried to fix this with commit e101419 but it hasn't worked.

The documentation:

https://docs.gravityforms.com/api-functions/#get-entries

says:

```IMPORTANT TIP: use paging to limit the number of entries otherwise you may find the database times out. On most servers we’ve found the optimum page size to be 200.```

So I'm going to double check the count that we should be getting and then implement paging for this, which will be slower.

**Comment by robmyers** [comment]
I've spent another couple of hours on this and I'm no closer to resolving it. :-(

**Comment by claudioruiz** [comment]
In any case we are not asking the database very often.
Just checked and today the export is limited to 200.

What if we show the results in pages with 100 items each? Is that possible?

**Comment by robmyers** [comment]
That means we should implement paging, as mentioned above, I will do this.

**Comment by robmyers** [comment]
I'm not going to implement paging for now, rather I have:

1. Implemented a solution to fetch all of the results for a given date range by using paging *internally*.
2. Set a given date range of one week to the current date for the query.

These measures ensure that the data is more manageable both for the server and for the admin user.
