### ISSUE TITLE
Implement new timings for the vouching process

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#239]
We should change the workflow to something like below. The idea is to shorten times for applications: 

* Requests vouch: Email to voucher.
* Next day: Email to voucher “Claudio is waiting for your vouch”
* Day 3: Email to voucher “Please remember to review Claudio’s vouching request - if you don’t vouch or decline within 5 days, you will automatically decline
* Day 5: Last Day: Review vouching request today please!
* Day 6: Your vouching request has been set to “declined”

@robmyers Let's work together in the text of the emails.

**Comment by claudioruiz** [comment]
@robmyers: I prepared [a new workflow](https://github.com/creativecommons/global-network-strategy/blob/master/docs/workflows/membership_workflow_revisited.png) to help you out.

**Comment by robmyers** [comment]
I've shared a document with you for working on the email texts.

**Comment by robmyers** [comment]
I'll deploy the code when we have those finalised.

**Comment by robmyers** [comment]
We now have both code and texts but I shouldn't deploy before going away for a couple of days so I will deploy as soon as I get back.

**Comment by robmyers** [comment]
This has now been deployed and activated on the site.
