### ISSUE TITLE
List Institutional Members

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#242]
Today we have no way to know who is an institutional member. They are not listed in the Members page, etc. 

We should have a page to list them. I'm putting this High Priority because we already have a number of Institutional Members and neither I or anybody has a way to know who they are and how to contact them.

**Comment by robmyers** [comment]
They are listed in the admin section of the site but not publicly.

We may be able to use BuddyPress for this or I can borrow the admin page for a custom page type or shortcode.

**Comment by robmyers** [comment]
This is more broken than expected.

Institutional members should not be listed in the membership list when searching for vouchers,

they should be listed separately and we try to do this when creating the "institutional-member" type in BuddyPress but it is not working,

so I need to both show institutional members separately and *not* show them when they shouldn't be.

I'll have to dig into this but it will take more time than expected.

In the meantime, for contact purposes, Institutional Members are listed in the admin section.

**Comment by robmyers** [comment]
OK, listing is working:

https://network.creativecommons.org/members/type/institution/

Next, exclusion from the main list (as instutions cannot vouch).

**Comment by claudioruiz** [comment]
Add to the [members screen](https://network.creativecommons.org/members/) (for logged members), a button to display Institutional Members
