### ISSUE TITLE
Remove application id=586

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#243]
Please.  If you need it, I can explain it on Slack. Let me know when it's done.

**Comment by robmyers** [comment]
I set the status to REJECTED, which removes them from the application list and stops them reapplying. Their user account still exists but has no permissions.

**Comment by robmyers** [comment]
Or we can roll their application back to CCGN_APPLICATION_STATE_DETAILS and I can delete any entries after that (particularly the vouching entries).

I've put them on hold for now.
