### ISSUE TITLE
Remove user_id=607

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#244]
Please remove this application because the person already has a valid application in process.

**Comment by robmyers** [comment]
We should come up with a way of phrasing these requests so I don't mistakenly go too far. :-)

The options we currently have for removing applications and/or applicants are:

1. Delete the user account and remove the application form entries. (delete the user, delete the application)
2. Set the application status to "paused" and lock the account so they cannot log in. (lock the user, pause the application).
3. Delete the form entries and lock the account so they cannot log in. (delete the entries, lock the user).
4. Delete the form entries and reset the application state so they can re-apply (delete the application, reset the application stats).

I am assuming 1 here.

**Comment by robmyers** [comment]
I've updated the descriptions above and this person is now a 1.

Deleted.
