### ISSUE TITLE
Provide Membership Council a way to ask for clarification for incomplete vouching statements

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#245]
- Maybe including a checkbox? We need a way to bounce back incomplete applications when the Membership Council don't have enough information about a certain applicant. 

- Maybe/also giving the admin powers to manually edit some fields on the application?

**Comment by robmyers** [comment]
Rob to explore options and detail here.

**Comment by peterspdx** [comment]
@sarahpearson Please include Sarah in any evaluation before a decision is made.
