### ISSUE TITLE
I don't understand user_id=614 status

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#249]
Don't have any vouches, but it's approved (?) Can you take a look at it to see what's going on?

**Comment by robmyers** [comment]
Membership Council Members can vote in parallel to the Vouching process to save time.

I can change "Approved" to "Voted For" to make this less misleading, or I can lock out the Membership Council from Voting until Vouching is complete (the latter will take longer).

**Comment by claudioruiz** [comment]
But what I see [in this case](https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application&user_id=614) is:
- The application don't have any vouch. 
- Actually, has 2 cannots.
- But 5 IMC votes (!!)
- And I can't approve it. I assume, because is not a valid application in the first place.

> Membership Council Members can vote in parallel to the Vouching process to save time.
1. How MC members **know** about an application not already vouched? AFAIK is not public for them until it's vouched.
2. Is there a way to avoid that to happen?
