### ISSUE TITLE
Add an option for Admin to ask applicants for better bio and statement before pre-approve

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#253]

**Comment by robmyers** [comment]
Worflow: flag/press button, email is sent, applicant can update bio.

**Comment by claudioruiz** [comment]
What about adding an option here

![image](https://user-images.githubusercontent.com/390030/43409744-bcf31f06-93f2-11e8-93ec-8bc7908104bb.png)

triggering an action: text box to add a message to the applicant asking to edit their bio/statement.

**Comment by robmyers** [comment]
I worked out a way to do this "cheaply" in terms of development time.

**Comment by claudioruiz** [comment]
How is that, Rob? I can’t find any new option in the menu.

**Comment by robmyers** [comment]
Oh it still needs doing. I just worked out a way. My apologies for the ambiguity.

**Comment by robmyers** [comment]
The note that you can now add to the form above when you select the "more info option" will be emailed to the applicant. It is substituted for the *|NOTE|* tag in the template under "Applicant Must Update Details".

Just to be clear:

WARNING: this note will be sent to the applicant! 

:-)

**Comment by robmyers** [comment]
You might also like to take a look at the "Applicant Must Update Details" template in the WP config.

**Comment by robmyers** [comment]
This has now been deployed to the live site. Let's discuss it on Monday.

**Comment by claudioruiz** [comment]
This is fantastic. Just one comment. 
Nice to have: a way of locking the possibility of sending by mistake twice a message as far once you send the "please update" email, you can send another again without any further warning. A warning it might be nice to have.
