### ISSUE TITLE
We need to check the timings of the notification system

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#262]
There's reports we are not giving enough time the applicants for updating their vouchers before we close them.

**Comment by robmyers** [comment]
I'm working on this but it's involved a rewrite of this part of the system. I wouldn't perform a rewrite at this point if it wasn't absolutely the best way to fix it. The code is written and I am testing it now but it is not yet deployed.

**Comment by robmyers** [comment]
I have finished this round of testing and checked the code in but I do not want to deploy this last thing. I'm going to test it some more tomorrow because it really is a major change, then I will deploy.

**Comment by robmyers** [comment]
I have tested the code further and deployed it to the Network site.

I have reset one applicant's status to make sure that this works as expected on the live site.

This has been a major code change so I will be monitoring the behaviour of the site closely for the next few days

Once I am sure that the site is functioning as expected we can start resetting the applications of other applicants that we need to.

I appreciate that this is a further delay but I believe this level of caution is warranted given the degree of change.

**Comment by claudioruiz** [comment]
I really do. Just tell me when it’s fully deployed to start using it.

**Comment by robmyers** [comment]
The system seems to be functioning well now.

We have reset the application of everyone who contacted us about this.
