### ISSUE TITLE
Review and document the applications workflow

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#281]
Basically, [update this](https://github.com/creativecommons/global-network-strategy/blob/master/docs/workflows/membership_workflow_revisited.png)

**Comment by hugosolar** [comment]
Ok, Workflow was written using [Mermaid](https://mermaidjs.github.io/#/) which is a way to write workflows or flux diagrams in a similar way to markdown.
The Mermaid syntax is placed [here](https://gist.github.com/hugosolar/3e752abdf2466d358715d14bb26bedd6) and can be seen as [SVG](https://drive.google.com/file/d/1QKVX98IECQMea4frdabrL0Cemki5g13I/view?usp=sharing) or in the (live editor)[https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbkFbQ0NJRF0gLS0-fExvZyBpbnwgQntBcHBsaWNhdGlvbn1cbkIgLS0-IENbSW5kaXZpZHVhbCBBcHBsaWNhbnRdXG5DIC0tPiBGW0FwcGxpY2F0aW9uXVxuQiAtLT4gRFtJbnN0aXR1dGlvbmFsIEFwcGxpY2FudF1cbkQgLS0-IEVbQXBwbGljYXRpb25dXG5FIC0tPiBHe1NwYW0gQ2hlY2t9XG5GIC0tPiBHXG5HIC0tPiB8WWVzfEh7QXNrIHZvdWNoZXJzfVxuRyAtLT4gfE5PfEl7RGVjbGluZX1cbkcgLS0-IHxBc2sgZm9yIGRldGFpbHN8SltVcGRhdGUgZGV0YWlsc11cbkogLS0-IHw3IGRheXN8SyggMXN0IFJlbWluZGVyKVxuSyAtLT4gfCs3IGRheXN8TCgybmQgUmVtaW5kZXIpXG5MIC0tPiB8KzMgZGF5c3xJXG5IIC0tPiB8WWVzfE1bVm91Y2hlcnMgb2tdXG5IIC0tPiB8Tm98SVxuSCAtLT4gfENhbm5vdHxOW1VwZGF0ZSB2b3VjaGVyc11cbk4gLS0-IHw3IGRheXN8T3tSZW1pbmRlcn1cbk8gLS0-IHwrMyBkYXlzfElcbk8gLS0-IHxWb3VjaGVycyB1cGRhdGVkfE1cbk0gLS0-IFBbTUMgVm90aW5nXVxuUCAtLT4gfD49IDUgdm90ZXN8UXtGaW5hbCBBcHByb3ZhbH1cblEgLS0-IHxOb3xJXG5RIC0tPiB8WWVzfFJ7IGZhOmZhLWRpcmVjdGlvbiB9XG5SIC0tPiB8SW5zdGl0dXRpb25hbHxTe0xlZ2FsIEFwcHJvdmFsfVxuUiAtLT4gfEluZGl2aWR1YWx8VCgoTWVtYmVyKSlcblMgLS0-IElcblMgLS0-IHxZZXN8VFxuc3R5bGUgVCBmaWxsOiNGRjk2OTYsdGV4dDojRkZGLHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDo0cHhcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19]
