### ISSUE TITLE
Fix bug: at "restarting" applications we should also restart the voting count

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#290]
See this https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application&user_id=614

I don't know why it has accepted votes, when it has no valid vouches. And appears as "approved", when basically is not yet a valid application.

**Comment by hugosolar** [comment]
I've made an extra function to delete user votes when the vouching status is restored in commit a42b8a80063b4ab42b624fb0a5553775ae7e347d 
But I'm still trying to figure out why and how the MC members can vote for an unvouched applicant.

**Comment by hugosolar** [comment]
Added a condition so the applicants can't be voted if they aren't vouched in commit https://github.com/creativecommons/commoners/commit/3bad86ceaaeaa2dc55781e0f24e628a0a931e5d0
