### ISSUE TITLE
Check why user_id=284 is wrongly listed on the Institutional member list

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#293]

**Comment by hugosolar** [comment]
The problem was that her name was on the "display name" field.
I changed it to the institution name but her personal picture is still there. Maybe we can advise her to change it

**Comment by claudioruiz** [comment]
ping @simeonoriko

**Comment by simeonoriko** [comment]
Asked. Can we change the url to reflect the name of the organization instead of her name? https://network.creativecommons.org/members/deborahdeangelis/
