### ISSUE TITLE
Make the Network site responsive 

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#294]
The website is not woking very well (specially the menu on top) when is visited on mobile.

**Comment by hugosolar** [comment]
Checklist
- [x] Clean old styles from style.css (just leave the theme metadata)
- [x] Clean transitional styles (file extra.css)
- [x] check responsiveness across the site
- [x] Move old styles to new Foundation/Sass workspace

**Comment by sivaraam** [comment]
Had the fix for this issue been deployed?
