### ISSUE TITLE
Improve the Application form

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#301]
The idea is to improve the quality of the applications. So, there's a couple of suggestions to implement (happy to talk about it):

* Force a minimum characters policy for the textbox, to avoid to deal with single line applications.
* An obligatory list of 3 demonstrable actions you've done for the Commons

**Comment by hugosolar** [comment]
Added new internal fields suggested by Membership committee

- Have you attended any CC (or open movement) event in the past? If yes, details … (only date, name, location, link maybe with limited character)
- Have you organised or contributed a CC (or open movement) event in the past? (Training/ workshops etc.)
- Have you ever developed an open content, tool, platform? 
- How would you like to contribute to the CC network? e.g. (perhaps a controlled list with multiple choice)
    - Advocacy (e.g. policy/ technical level; national/international or list of topics?)
    - Deliver training, run workshops (if yes, areas?)
    - Develop open content (if yes, areas?)
    - Legal support
    - Other
