### ISSUE TITLE
Search does not work properly 

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/commoners#311]
I was looking for a specific confirmed institutional member: "Open State Foundation" and found nothing when looking for "open state". When looking for "state" the member did show up.

Link to reproduce:
https://network.creativecommons.org/members/type/institution/?members_search=Open+state&members_search_submit=Search

**Comment by hugosolar** [comment]
Moving this to the Redesign issues. I would like to integrate Elastic search to the CCGN or at least rewrite the directory avoiding buddypress members filters and unnecessary ajax. This should be related to #283

**Comment by hugosolar** [comment]
Fixed in redesign with the revamping of the whole members' search
