### ISSUE TITLE
Update Network Website's developer community URL

### ISSUE THREAD

**Issue by kgodey** [creativecommons/commoners#315]
The Network website https://network.creativecommons.org/get-involved/ has the following paragraph under "Contribute Your Skills":

> Are you a developer?. Learn about how to integrate CC license information. Join our developer community. Check out our page on github and help us improve our tools.

Could you change this to:

> Are you a developer? Join our [developer community](https://creativecommons.github.io) to learn about how to integrate CC license information and help us improve our tools.

And remove any other URLs from the text other than the one I specified above.

You can keep the prior line about translations as-is.

**Comment by hugosolar** [comment]
Done in https://github.com/creativecommons/commoners/commit/9498e467b3b1b5bf9301b7fa479d1c8c5191d85e
