### ISSUE TITLE
Change "Application state" update-details in the Spam Check window

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#316]
we should pick something clearer for the clarification status on the Spam Check such as what we have on the Application Approval window (colors, etc)

Today's status:

- `received`: when the application has been received OR the application has been updated after requirement
- `update-details`: when we requested the applicant to provide more information and complete the Membership Statement and/or Bio. 

Suggestion:

- `received`: when application has been received and is waiting for being pre-checked. I'm not sure if we need an status for this, but anyway. 
- `requested info` (in orange?): when applicant has been requested to provide more info about its application
- `received` (in yellow?): when applicant has provided more information and is now waiting for being pre-checked. 

what do you think?

**Comment by hugosolar** [comment]
Improvements made in 5af3e03
- Replace old plain table with datatable
- Add row colors to 'asked for details' and 'details updated' status
- Change text to clarify current user status
