### ISSUE TITLE
profile pages on network leads to back-end wordpress

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/commoners#318]
I went to https://network.creativecommons.org/members/
Logged in
an click on profile

I expected to see a profile page (as I did a couple of days ago), but was redirected to Wordpress backend. Is this the current workflow?
![image](https://user-images.githubusercontent.com/5627431/35437489-ea5c73d0-0292-11e8-81a8-1ceb211e7f0c.png)

**Comment by mzeinstra** [comment]
Happy to vouch for your membership to the Creative Commons Global Network ;)

**Comment by hugosolar** [comment]
Now the "Profile" option in the navigation menu leads to the buddypress profile page
