### ISSUE TITLE
Menu bar looks the same whether you are logged or not 

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#32]
I think the design mockup it's different here

![image](https://user-images.githubusercontent.com/390030/31508553-d3fc5be6-af54-11e7-8bde-82140eb49310.png)

**Comment by robmyers** [comment]
We can achieve that with this plugin -

https://en-ca.wordpress.org/plugins/nav-menu-roles/

**Comment by claudioruiz** [comment]
great idea. please do it.

**Comment by robmyers** [comment]
Using If-Menu, as it works better for our use case.

**Comment by robmyers** [comment]
The mock-up does have a slide that mentions differences for logged-in users, but the content is the same as the previous slide.

**Comment by robmyers** [comment]
I'd like to push this back to after launch or hand it over to someone else.

**Comment by robmyers** [comment]
Create top & bottom menus.

Hide appropriately.

**Comment by robmyers** [comment]
Done. (WP config, no commit to reference.)
