### ISSUE TITLE
Make repository contribution ready

### ISSUE THREAD

**Issue by kgodey** [creativecommons/commoners#321]
See: https://wikijs.creativecommons.org/tech/github-repo-guidelines

- [x] Code owners should be defined in the [`CODEOWNERS` file](https://help.github.com/en/articles/about-code-owners) in the `.github` directory in the project root.
- [x] Add Code of Conduct in a [`CODE_OF_CONDUCT.md` file](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project) in the root directory. We can use the standard file from our [`.github` repository](https://github.com/creativecommons/.github).
- [x] Add project-specific contributor guidelines in a [`CONTRIBUTORS.md` file](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) in the root directory. The standard file from our [`.github` repository](https://github.com/creativecommons/.github) can be used as-is or as a starting point.
- [x] Add the standard [CC metadata YAML file](/tech/open-source/cc-open-source-website#cc-metadata-file).

**Comment by hugosolar** [comment]
Done in 07c9516
