### ISSUE TITLE
page 2 of "members" shows 1600+ active with dummy accounts

### ISSUE THREAD

**Issue by tvol** [creativecommons/commoners#328]
might be related to #307 

**To Reproduce**
visiting https://network.creativecommons.org/members/, logged in, pg 1 shows "Viewing 1 - 20 of 391 members"

but then clicking to page 2 shows "Viewing 21 - 40 of 1,638 active members" and several seem to be empty profiles
![Screen Shot 2019-04-02 at 4 54 30 PM](https://user-images.githubusercontent.com/231665/55443761-b7325680-5568-11e9-96ac-6d3b517ee14a.png)

![Screen Shot 2019-04-02 at 4 54 46 PM](https://user-images.githubusercontent.com/231665/55443772-bbf70a80-5568-11e9-8df4-c4e7b7e76314.png)

**Expected behavior**
expected to see page 2 with next completed profiles of network members (next in line alphabetically of ~391)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by hugosolar** [comment]
I was looking through the code and a filter is applied when the users where showed but that filter does not work when the page is changed. 
Seems to be a budypress bug, I'll have to research more about the filter and why isn't applied on pagination. 
The buddypress [documentation](https://codex.buddypress.org/developer/function-examples/bp_ajax_querystring/) shows the filter as the only way to do that.
For now, the only solution I can think is to rebuild the members' list not using buddypress and it's annoying ajax search & pagination.

**Comment by hugosolar** [comment]
The ajax pagination lost the wordpress context and doesn't know in which section is it. That's why the filter does not work on page 2 henceforth. The solution will be temporary until redoing the members directory without ajax
