### ISSUE TITLE
Former members of the MC with empty profiles after removing their privileges

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#329]
After removing MC privileges to a group of members, their profiles seems now "empty" of any content not able to log in. This was reported by email and it was reproduced by me and @hugosolar. 

It's important to sort this out ASAP.

**Comment by claudioruiz** [comment]
This might be connected w https://github.com/creativecommons/commoners/issues/328

**Comment by hugosolar** [comment]
Ok, finally there was no problem at all
When the network started the former members of the MC were added in a direct way avoiding the regular process so they never had vouching, voting or personal data related to them, this is not affecting they login or their vouching / voting history.
