### ISSUE TITLE
Fix the Network Page link

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#331]
> I just wanted to let you know that the “Read More” link under Chapters is broken on the page below. It looks like all of the links at the bottom of that page are, actually.
 
> https://network.creativecommons.org/?ref=global-affiliate-network

**Comment by hugosolar** [comment]
Fixed in https://github.com/creativecommons/commoners/commit/4b59a62984515efea42e16ce127c458e6136cbec
it was a hardcoded link
