### ISSUE TITLE
Improve messaging around CC Open Source

### ISSUE THREAD

**Issue by kgodey** [creativecommons/commoners#342]
CC Open Source is currently linked at https://network.creativecommons.org/get-involved/writing-code/. I'd like a couple of changes

- The "Creative Commons open source" button does not link to anything. It should link to https://opensource.creativecommons.org/.
- Please capitalize "Open Source" so that it's "Creative Commons Open Source".
- The text currently says:
    > Creative Commons has been building free software for over a decade to support our mission of maximizing digital creativity, sharing, and innovation. Our projects come in all sizes and shapes, from simple static websites to building fast and relevant search interfaces to the 1.6 billion+ Creative Commons works currently available on the internet. Our engineering team is fairly small and spread thin, so we’re really appreciative of volunteers who help us build or test our software.

    Could we change it to:
    > Interested in integrating CC tools into your application or helping us build our open source software?
- I would like to direct users to CC Open Source even if they can't code. For example, they could contribute design or just use our products and give us feedback. I don't have a specific suggestion, whatever you think works.

**Comment by Atanda1** [comment]
I'll like to work on this

**Comment by kgodey** [comment]
This is not open to community contribution right now.

**Comment by valerio-bozzolan** [comment]
As already reported, please fix the "Creative Commons open source" button, since it does not link to anything.

https://network.creativecommons.org/get-involved/writing-code/

It seems not possible for me to help in any way, since I have not WordPress credentials and/or this part does not appear in the available source code.

**Comment by xolotl** [comment]
Thanks for your nudge @valerio-bozzolan!

The button is now properly linked and text on the page is updated to say:

"Creative Commons builds free and open software to support our mission to maximize digital creativity, sharing, and innovation. Our projects come in all sizes and shapes to help people add to and engage with the 2.5 billion+ Creative Commons works on the internet. The CC technology team is fairly small and spread thin, so we really appreciate volunteers who help us build, test, and document open software.

Interested in integrating CC tools into your application or helping us build free and open software?"

**Comment by valerio-bozzolan** [comment]
Thank you a lot @xolotl it seems OK for me! I just also suggest to write "Free" instead of "free" (it's a widely used trick to stress the fact that we like software Freedom, and it's not related to produce proprietary freeware). Thank you so much

**Comment by valerio-bozzolan** [comment]
Also I can suggest to improve the link removing the `target="_blank"` HTML attribute, so the link opens in the same tab, just like the other links.

I have not  a strong opinion on this small improvement but the destination is not an extra page (like "see privacy info" etc.) but it's the natural navigation flow, suggested from that landing page, so I think it's more natural to keep the link as-is (without opening in new window).

Sorry ahah :D thank you!

**Comment by xolotl** [comment]
@valerio-bozzolan Thank you for the additional suggestions! I have set the button link to not open in a new tab/window.

It may be a small thing, but the capitalization of "free" (as in _libre_, not _gratis_) is not currently covered in the [CC style guide](https://creativecommons.org/wp-content/uploads/2019/10/Creative-Commons-Style-Guide-2019.pdf). When something like that is not covered, one thing we sometimes do is see how it is handled by sister organizations, for example [Wikipedia](https://en.wikipedia.org/wiki/Free_software) or even the [Free Software Foundation](https://www.fsf.org/). In my research, neither capitalizes "free" when it is not the beginning of a sentence, or covered by other capitalization practices.

While CC could capitalize like "Free" or add "_libre_" to clarify for readers, that practice is followed systematically nowhere else in all CC websites or publications and so to do it here on this single page would be inconsistent. I don't think there's enough motivation to undertake the very large project it would be to change practices across all CC publications.
