### ISSUE TITLE
Application Status shows on homepage

### ISSUE THREAD

**Issue by kgodey** [creativecommons/commoners#345]
I have an admin CCGN account but I see the Application Status progress bar on the homepage. I don't think a lot of people will have this bug so it's low priority.

![Screenshot_2019-07-15 CC Global Network Community Site](https://user-images.githubusercontent.com/287034/61569994-050b9580-aa58-11e9-9d82-e571db9d5758.png)

**Comment by hugosolar** [comment]
filter added in 1c3ee08
when the user is added or role-updated to `administrator` the system will assign the membership metadata (accepter individual member)
