### ISSUE TITLE
small countries cannot select 'more informarion' on map

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/commoners#356]
On the new chapter map pages it is impossible to go to the pop-up with the more information button for the smaller countries that have countries to their east with chapters.

This is an issue with the Netherlands, Bulgaria and Venezuela.

**Comment by hugosolar** [comment]
Hey @mzeinstra 
I couldn't reproduce this error but closed ticket #371 may have fixed this issue as well
can you please confirm that?

**Comment by mzeinstra** [comment]
still occurs for me. See attached gif.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5627431/71259612-20e1d300-2339-11ea-8884-ec8234530e79.gif)
