### ISSUE TITLE
Add new questions to the Application Form for new members

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#361]
- [ ] Have you attended any open movement-related event in the past? (ex. CC Global Summit)
 - [If the answer is yes, open text box] – 
 - [In the explanation box, add: Please share any details of that, for example, date, name, location, or other relevant detail)

- [ ] Have you organized or contributed an open movement-related event (such as a training, workshop or similar) in the past? (ex. CC Global Summit)
 - [If the answer is yes, open text box] – 

- [ ] Have you ever developed an open content, tool or platform?
- [If the answer is yes, open text box] – add [If yes, specify what tool or platform or any other relevant detail]

- [ ] Have you ever worked in the open knowledge or free culture space? If yes, please specify e.g. how/when. 

- [ ] How would you like to contribute to the CC network? 
 - Advocacy (e.g. policy/ technical level; national/international or list of topics?)
 - Deliver training, run workshops (if yes, areas?)
 - Develop open content (if yes, areas?)
 - Legal support
 - Other (please specify)

**Comment by clhendricksbc** [comment]
For the third question, can we word it as follows?

Have you ever developed or contributed to developing open content, or an open tool or platform?

**Comment by ilkayholt** [comment]
Christina, re. 3rd question, your wording is much better. Perhaps if we use "software" instead of a "tool" in the sentence, then it will also answer Claudio's question too. In reply to this question, people can have their work anything related to a OER, software or an infrastructure. In the open text box, "please specify" should be sufficient.

**Comment by clhendricksbc** [comment]
Sorry for the delay in replying! Yes, let's try the following for the third question:

Have you ever developed or contributed to developing open content, open software, or an open platform?

Sound okay @ilkayholt ?

And also, regarding the question about working in the open knowledge or free culture space--as discussed over email, I think keeping the question as is, and adding Ilkay's suggested parenthetical explanation at the end will work:

Have you ever worked in the open knowledge or free culture space (e.g., through activism or advocacy)? If yes, please specify how and when.

**Comment by hugosolar** [comment]
Form modified and added to applicant information in backend in commit 
0c438b3

**Comment by ilkayholt** [comment]
I can see the improvements on the submitted forms now. Thanks Hugo.
