### ISSUE TITLE
Change ID 2415 from institutional applicant to individual applicant

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/commoners#366]
@hugosolar This in reference to this application https://network.creativecommons.org/wp-admin/admin.php?page=global-network-application&user_id=2415

Brian made a mistake an signed up for an institutional membership instead of an individual one. Please change this membership for him.

Also, this is the third time this is happening in the last month. Is there something on the redesigned site that may be causing this? Worth investigating.

**Comment by kgodey** [comment]
@simeonoriko could you make a separate ticket for this part?
> Also, this is the third time this is happening in the last month. Is there something on the redesigned site that may be causing this? Worth investigating.

We may be able to update the design or allow users to switch the type of membership themselves before it is submitted.

**Comment by hugosolar** [comment]
@simeonoriko the user application type was successfully changed.
