### ISSUE TITLE
Investigate high number of institutional membership applications made in error

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/commoners#367]
In recent weeks we've had a number of people intending to sign up for individual accounts but for some reason they end up signing up for institutional accounts.

Please investigate cause of this error and a solution to fix it.

**Comment by hugosolar** [comment]
I investigate this problem and my thoughts are these:
- There was a confusion about the status management in the code. the code assumes an institutional type when you don't have any member type
- When an applicant is logged in there was no way to choose institutional or individual form

The fix in this commit  15a8cd7 contains the following fixes
- fix member type in green status bar
- Add option in user-status widget to choose between individual or institutional application form
- Add sidebar (with both application forms widget)  showed when the user is logged in, not accepted yet and do not have a member type yet

I'm going to close this issue, if the problem persists, we can reopen it again
