### ISSUE TITLE
Investigate rejection workflow

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/commoners#368]

**Comment by hugosolar** [comment]
User should be rejected when

- Spam check is marked as `no`
- Spam check marked as `update details` and this doesn't happen in the next 24 days
    - First reminder at first 7 days
    - Second reminder in next 7 days
    - 10 days after not responding, the application will decline
- Voucher vote `NO` (this is expected behavior but it's not happening)
- passing 10 days after asked to update vouchers because `cannot` 
- Final approval marked as `no`

**Comment by claudioruiz** [comment]
rejected = can apply again immediately 
denied = application stopped by MC
