### ISSUE TITLE
CC Hong Kong not highlighted on map

### ISSUE THREAD

**Issue by simeonoriko** [creativecommons/commoners#371]
**Describe the bug**

CC Hong Kong isn't highlighted on the map here: [](https://network.creativecommons.org/chapter/). It is however listed in the list view.

**To Reproduce**
Visit the chapter page on the network site and look for Hong Kong on the map (close to Taiwan which is highlighted)

**Expected behavior**
Hong Kong should region should be highlighted in green.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 78.0.3904.70 (Official Build) (64-bit)

**Comment by hugosolar** [comment]
Hong kong actually exists in the map but it's tiny and it can't be seen
![Screen Shot 2019-12-16 at 12 18 19 PM](https://user-images.githubusercontent.com/894708/70918680-3a63e180-1ffe-11ea-8171-b66b662caaac.png)

One possible solution is to add control to zoom and move the map
What do you think @claudioruiz ?
