### ISSUE TITLE
We should impede MC members to vote for applications already vouched or declined by them

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#390]
That's it.

**Comment by hugosolar** [comment]
Ok, I've found this actually happens now and I didn't know that
I run a test on my dev environment and this is what I saw

![Screen Shot 2020-04-14 at 8 54 35 AM](https://user-images.githubusercontent.com/894708/79227378-cad7f480-7e2d-11ea-91be-9c53afd1dcad.png)
