### ISSUE TITLE
Process of removing voucher

### ISSUE THREAD

**Issue by Juliabrungs** [creativecommons/commoners#394]
It happens that a voucher will need to be removed from an application (normally the decision is taken by the Membership Committee). We need a process on how to do this.

**Comment by hugosolar** [comment]
@Juliabrungs I have a question regarding this issue... should we need to keep this reason hidden for other MC members? Because I remember a while ago this was a concern in terms of privacy and it was a decision not to ask a reason.

**Comment by Juliabrungs** [comment]
Hi Hugo,

I don't think so. Basically the background for this is the following. 
One of the vouchers says no, this person should not be a Network Member. The application then goes to the whole MC to be evaluated and the MC takes a decision if the vouchers statement is correct or should be overruled. 
If they hold the vouchers statement - the application gets rejected. 
If they decided that the voucher statement is not valid and overrule it, we need a process to remove the voucher, re-open the application and let the applicant pick a new voucher.
