### ISSUE TITLE
MC member votes no - holds application

### ISSUE THREAD

**Issue by Juliabrungs** [creativecommons/commoners#396]
When one MC member has voted no, the application should be on hold until review by the MC and no other MC members should be able to vote on it.

**Comment by hugosolar** [comment]
@Juliabrungs I have a question regarding this issue
what's happen when the MC approves or deny this review?

**Comment by Juliabrungs** [comment]
So the idea is that when an MC member votes 'no' the application automatically closes and is rejected and no other MC member can vote on it. I then send an email and the MC reviews the application. If they come to the conclusion that it is indeed a 'no' vote, the application gets rejected. If a majority thinks the application is fine, the 'no' vote is removed and the application is voted on by 5 members. Does that make sense?

**Comment by hugosolar** [comment]
So I'll follow these steps
- If the applicant gets a 'no' vote the application can't be voted anymore and it gets marked on the Applications for appoval list 
- I'll reuse the same MC review form we're using when a user gets a 'no' vouch
- If the MC resolves the issue as a 'Yes'
  - the 'no' vote is removed and the applicant status is back to the voting stage
- If the MC resolves the issue as a 'No'
  - the Application is declined and the user is notified

**Comment by Juliabrungs** [comment]
Yes! That is it!
