### ISSUE TITLE
Application approval open application

### ISSUE THREAD

**Issue by Juliabrungs** [creativecommons/commoners#397]
Hi Hugo,
There are 4 applications in the application approval stage from 2018. They were asked to provide new vouchers and never did so they should have automatically failed after 21 days but they are still there. Why and how can we fix this?

Thanks!
Julia

**Comment by hugosolar** [comment]
Ok. done
I deleted the following accounts:
ID #705: sailesh.patnaik007@gmail.com
ID #724: sidheeq@gmail.com
ID #720: ponakala928@gmail.com
ID #814: ifeomashodeinde@gmail.com
