### ISSUE TITLE
network.creativecommons.org shows Wordpress favicon

### ISSUE THREAD

**Issue by mbutel** [creativecommons/commoners#399]
## Describe the bug

network.creativecommons.org shows Wordpress favicon
/favicon.ico refers https://network.creativecommons.org/wp-admin/images/w-logo-blue.png
## To Reproduce

1. Go to 'https://network.creativecommons.org/favicon.ico'

## Expected behavior

Show CC logo
## Screenshots

![image](https://user-images.githubusercontent.com/6067949/81009274-b7b3b580-8e2a-11ea-990a-a6c0343ca9fd.png)

**Comment by hugosolar** [comment]
Fixed.
Thanks @mbutel for pointing this out
