### ISSUE TITLE
Get Copy On Site

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#42]
Replace placeholders for ToS etc.

**Comment by robmyers** [comment]
Added intermediate versions.

**Comment by robmyers** [comment]
@peterspdx @sarahpearson tagging you in this so we can keep track of its progress.

**Comment by robmyers** [comment]
We have the charter.

We need the PP and the ToS.

**Comment by peterspdx** [comment]
It's going to be another 24 hours on the PP and ToS based on conversations just ended. We're super close, though! Another update will be to the cc.org/policies page. Edits previously send, but checking again to make sure updated and then I'll send.

**Comment by robmyers** [comment]
Thank you!
