### ISSUE TITLE
Email Institutional Applicant To Let Them Know Legal Will Be In Touch

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#50]
When an Institutional Applicant receives "Final Approval" and moves to the Legal Approval stage, email them to let them know that Legal will be in touch.

We could add a hidden "Applicant Type" field to final approval so we can use conditional logic to only notify on Institutional applicants.

Or we could add this in to the "Final Approval" form hook. 

Either way, Legal don't need to know when Individual applicants get Final Approval. Just Institutional applicants.

**Comment by robmyers** [comment]
I created an email for this, @claudioruiz you might like to take a look at it to make sure it makes sense

**Comment by claudioruiz** [comment]
@robmyers Looks fine to me. Please adopt it.

Please see #214
