### ISSUE TITLE
Vouching Request List Page for Users

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#51]
Generate a page listing vouch requests for users.

We should probably have the vouching shortcode list pending requests if applicant_id is specified.

This is going to be slightly computationally intensive - vouch requestee IDs are stored in multiple fields of the Vouch Request form. Try to capture and cache these in a user metadata property at form save time and then clear them when the user vouches (have a function to completely rebuild these for safety's sake).

**Comment by robmyers** [comment]
@claudioruiz this is the enhancement ticket I mentioned.

**Comment by claudioruiz** [comment]
Yeah, I'm sorry but we will need this.

**Comment by robmyers** [comment]
Hey no it makes sense, that's why there was an enhancement issue for it already. :-)

Implemented in f05dba6.

We should add a conditional link to it to the top of the page for logged-in Members.

**Comment by claudioruiz** [comment]
> We should add a conditional link to it to the top of the page for logged-in Members.

I don't see that implemented. IMC members still see the long list of applicants (with and without vouchs) under the Membership Applications for Approval screen.

**Comment by robmyers** [comment]
Done.
