### ISSUE TITLE
Add JS To Vouching Form To Remove Chosen Users From Other Selects

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#55]
Select someone? Remove their name from other selects.

Deselect them? Re-add them to other selects.

**Comment by hugosolar** [comment]
I just disable the chosen person in the next or previous select so it can't be selected

![captura de pantalla 2018-11-29 a la s 15 20 34](https://user-images.githubusercontent.com/894708/49242825-7d9ae480-f3ea-11e8-9b52-78e5b19e0623.png)
