### ISSUE TITLE
Add Profile Link Display Below Selects In Voucher Choosing Page

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#64]
Use JavaScript to dynamically add a link to the selected user underneath the select so that the user can open the profile in a new window to double check.

**Comment by robmyers** [comment]
This will be a chunk of work, but nice to have.

Good task to assign to a volunteer?

**Comment by robmyers** [comment]
Also add an image.

**Comment by hugosolar** [comment]
Added a profile link when a user is selected in the choose vouchers section of the applicant form.
the link opens in a new window

![captura de pantalla 2018-11-29 a la s 17 25 46](https://user-images.githubusercontent.com/894708/49249995-81376700-f3fc-11e8-9b10-18af18843326.png)
