### ISSUE TITLE
Let Institutional Applicants Know They Can Set An Image After Approval

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#69]
We don't require one during sign-up.

**Comment by robmyers** [comment]
We don't require them of either Individual or Institutional applicants.

But we do mention a photo on /sign-up/individual/

We should remove that and mention that you will be able to add a photo in the "once you have..." sections on /sign-up/individual/ and /sign-up/institution/ .

And we should mention it in the confirmation email if we don't already.

@little-wow is this me or you? :-)

**Comment by little-wow** [comment]
I trust you to do it @robmyers provided you don't use any silly British spelling ;-)

**Comment by claudioruiz** [comment]
Not sure if this is solved, @robmyers

**Comment by hugosolar** [comment]
I added two new replacement strings to the global network emails

- *|APPLICANT_PROFILE_EDIT_URL|* : URL to the edit profile section
- *|APPLICANT_PROFILE_CHANGE_AVATAR|* : URL to the "change avatar" section

Now we can remind the applicants in the confirmation email to update their profile or add an avatar image
