### ISSUE TITLE
Set Scrubbing Level

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#70]
@peterspdx - let me know the decision and I will tweak the code.

**Comment by robmyers** [comment]
Obviated.

**Comment by robmyers** [comment]
Scrub stated fields.

**Comment by robmyers** [comment]
After 21 days.

**Comment by robmyers** [comment]
Finish ccgn_cleanup_old_records .

**Comment by claudioruiz** [comment]
I don't know what is this. I can't prioritize.
