### ISSUE TITLE
Homepage box wrongly aligned 

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#72]
![image](https://user-images.githubusercontent.com/390030/32136626-da7b3c24-bc08-11e7-997c-69dcc9160381.png)

**Comment by robmyers** [comment]
Which browser / os combination please?

**Comment by claudioruiz** [comment]
OSX / Chrome Version 61.0.3163.100.
OSX / Firefox 57.0b9

**Comment by robmyers** [comment]
Fixed. Related to #75 and masked by that issue on my development machine.
