### ISSUE TITLE
Re-size the `entry` div?

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#73]
This is true for the entire page, but specially on long text pages such as the charter (even using full screen). This is particularly bad when you are not using fullscreen but a portion of it. 

Is it possible to let more space to the central part of the page and not so much to the `footer` and the `head`?

![image](https://user-images.githubusercontent.com/390030/32136643-308f1234-bc09-11e7-99fd-d92e64a68c28.png)

**Comment by robmyers** [comment]
I made it larger by shrinking the top and bottom areas.

This required a chunk of css hacking. The shadow below the top menu doesn't appear at every page width but I don't have time to fix that atm. Things also look bad without the WordPress menu bar, which I assume most people will not remove.
