### ISSUE TITLE
Improve the readibility/design of the Charter

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#76]
The CSS does not look very polished (different fonts, diff alignment, etc.

**Comment by edmillag** [comment]
Header not needly should be fixed to the top

**Comment by robmyers** [comment]
This is a copy and paste of the rendered markdown.

I agree it needs to look better.

**Comment by robmyers** [comment]
The header is from the markdown. Having it on the page helps to keep the page title short, means I literally just ciopy the rendered markdown and don't have to remember to change anything, and (trivially) helps when inlining it in the "Sign The Charter" step of the Individual Member Application workflow. But we could as easily add the title there manually.
