### ISSUE TITLE
Number of Vouchers

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#87]
At present, to help if people choose vouchers who are on vacation or otherwise unable to respond to vouching requests in a reasonable amount of time, we let people select additional, optional vouchers.

Two vouches are required for the applicant to go to the Final Approval stage. More vouches would not help, and will be ignored.

A single vouch against the applicant will disqualify their application.

Rather than trying to include fallbacks in the code of the site, it may be better to just have the two required vouchers.

We can then remove the Optional voucher fields from the form, making it simpler for the applicant.

Where there is a problem contacting a voucher, this then becomes a problem for the membership council to address.

To reduce the number of such problems, the form should inform the applicant that they should make contact with them to make sure they are willing and able to vouch quickly prior to submitting the vouchers' names in the form.

Can we make this change?

Here is the current form (not styled with the theme from the site!):

![image](https://user-images.githubusercontent.com/21746/32304360-e3468f18-bf2b-11e7-9f69-910321aeffe0.png)

**Comment by peterspdx** [comment]
I support eliminating the optional vouchers, for the reasons stated. We can always change later if this becomes a problem, in consultation with the network council. +1 to removing third, fourth and fifth.

**Comment by claudioruiz** [comment]
I've been thinking on this and I think we should just eliminate the optional vouchers. This is not in the strategy and was not a decision of the Transition Group, so because of the time constraints, I would say eliminating them under the same assumption than @peterspdx above.

**Comment by robmyers** [comment]
New layout (unstyled!) -

![image](https://user-images.githubusercontent.com/21746/32353911-9b045d98-bfe4-11e7-8e4b-89e75eabe7e9.png)
