### ISSUE TITLE
Markup the vouching emails

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#93]
By now, this is what I receive: 

![image](https://user-images.githubusercontent.com/390030/32465295-c5975304-c321-11e7-857f-e17a34e8b278.png)

I guess we may do better with the text of that email to make it human readable. Happy to help, but I don't know who is receiving that email.

**Comment by robmyers** [comment]
Ugh. Let me think about how to improve that.

**Comment by robmyers** [comment]
OK it now sends a link to the applicant's approval page.

**Comment by claudioruiz** [comment]
Where can I check that email?

**Comment by robmyers** [comment]
It's in the Gravity Forms "Notifications" section but I've removed it for now.
