### ISSUE TITLE
need more vouchers to populate in list

### ISSUE THREAD

**Issue by tvol** [creativecommons/commoners#94]
Seems like only versions of "rob" populate in the pull down, even though there are several other "users" already signed up. perhaps those have not yet been "vouched" yet either? 
![screen shot 2017-11-07 at 3 33 20 pm](https://user-images.githubusercontent.com/231665/32523689-4257d936-c3d1-11e7-8cf6-f30b16e92689.png)

**Comment by robmyers** [comment]
They haven't been approved as members yet, though. Only fully approved members can vouch.

**Comment by robmyers** [comment]
Although this raises a good question - Membership Council members should be able to vouch during the initial "bootstrapping" phase, I need to double-check that's working.

**Comment by claudioruiz** [comment]
@robmyers yup: 
* On day 0: Membership Council can both vouch and approve (Same person can't vouch *and* approve obviously)
* From day 1 (when new members are accepted): Members (including IMC) can vouch others and those applications are reviewed by the Membership Council.

**Comment by robmyers** [comment]
That's good.
