### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#95]
![image](https://user-images.githubusercontent.com/390030/32572571-c62253c6-c4a9-11e7-8342-9b8c41e818de.png)

This search result (should be showing a kind of 404), not this.

Two questions:

1. If I'm not logged in, what am I finding? 
2. I looked for 'Rob' and the result included the text of the Charter (?) and the Sign Up page (try it)

I guess the search box should be looking for just the data of the users, not other documentation.

**Comment by robmyers** [comment]
I agree that the page should not look like this.

Member search is at the top of:

https://commoners-staging.creativecommons.org/members/

Do we want site search to just point to that or do we want people to be able to find e.g. the Insitituional Sign Up instructions or the Get Involved page by the text on it?

**Comment by claudioruiz** [comment]
Considering all of this website is about is the network and its members, I guess all the search should be aligned with that. That is the search is about the members data and metadata, not about the 'pages' we have on the BuddyPress backend (Charter, sign-up, etc).

What about having a 404 with:

* an animal image saying sorry (why not?) 🐶
* some super nice text saying sorry we didn't find what you are looking for but:
 * If you are looking for more information of how get involved with CC, this is the place ([link to `/get-involved`](https://github.com/creativecommons/commoners/issues/103))
 * If you are looking for a list of members, this should be the place (link to that member list)
 * If nothing of this is what you are looking for and you need some guidance, contact us (link to `/contact`).

What about that?
