### ISSUE TITLE
Removing the Charter?

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#96]
As far we already have a _canonical_ version of the Charter on the CC WP, are we still including an HTML version on the site? such as here: https://commoners-staging.creativecommons.org/charter/

I guess not

**Comment by robmyers** [comment]
We've removed the html version under network.cc.org/charter/, and the links on the site now point to the canonical url on cc.org.

In the form where the Applicant must sign the Charter, there is still an HTML version displayed to them there as we wish to make sure they have read it. This version is in an HTML element in the "Sign The Charter" form.
