### ISSUE TITLE
Add more areas of interest

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#97]
Now:

![image](https://user-images.githubusercontent.com/390030/32573215-ff721b3c-c4ab-11e7-836e-93d7073d73da.png)

My suggestion:
* Arts & Culture
* Education / OER
* Legal
* Open Access
* Open Data
* Open Science
* Policy / advocacy / copyright reform
* Technology
* GLAM
* Community Development
- Remove Regional Chapters

**Comment by robmyers** [comment]
The ones currently listed on the form are Platforms. So when the Applicant selects them, we can use this to match them up to platforms.

Will these all be Platforms? If not that's cool, I just want to make sure I've understood the use case.

**Comment by peterspdx** [comment]
I think the point is, people may be interested in many things not just platforms, and to cast a wider net in terms of interest rather than limiting them to existing platforms could be useful. I like the longer list provided. It will help inform future platforms and other ways to engage. My 2 cents.

**Comment by robmyers** [comment]
Yes if that's the case it's a minute's work to change, I'm just making sure I'm not breaking part of any workflows that assume a 1:1 mapping of this to Platforms. I agree that the longer list is better as a list of potential interests

**Comment by claudioruiz** [comment]
Yes, that's exactly my way of thinking, @peterspdx. This is not a form for people joining platforms, but to gather some basic information about their interests for better understanding about our network in the future. 

Please Rob make this happen 🙏
