### ISSUE TITLE
It's possible to apply with just one vouch

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#98]
![image](https://user-images.githubusercontent.com/390030/32573459-d455bb42-c4ac-11e7-85d7-b5591bbadd31.png)

I did this and my application was accepted.

**Comment by robmyers** [comment]
Development mode was turned on on the staging server, so it was possible to do this (as defined in ccgn_choose_vouchers_validate() in plugins/cc-global-network/includes/gravityforms-interaction.php ).

I have switched staging to "Testing" mode, which requires fewer vouches and votes but will enforce the logic of requiring different vouchers in this form.
